### ISSUE TITLE
fluffychat broken

### ISSUE THREAD

**Issue by selfisekai** [A-d-r-i/update_choco_packages#16]
the package downloads the source code, not a build, and does not build it

**Comment by A-d-r-i** [comment]
Thanks for the alert! It's fixed (+ integration of a verification) in https://github.com/A-d-r-i/update_choco_packages/commit/d2a555431d14a8b135d1a7d12156c82282b144ae

I sent a patch version of 1.11.2 as of today ( https://community.chocolatey.org/packages/fluffychat/1.11.2.20230613 ), it will soon be the main version in Chocolatey. The developers have not yet built the 1.12.0 version for Windows.
