### ISSUE TITLE
Tenacity 1.3 Stable Released

### ISSUE THREAD

**Issue by Timecrash** [A-d-r-i/update_choco_packages#17]
I left a comment on Chocolatey, but just wanted to make you aware Tenacity 1.3 has released, thus replacing Saucedacity.

<https://codeberg.org/tenacityteam/tenacity/releases/tag/v1.3>

**Comment by A-d-r-i** [comment]
Thank you for the message but I am already aware, you can install Tenacity 1.3 here:

https://community.chocolatey.org/packages/tenacity/1.3.0
