### ISSUE TITLE
Filen package is outdated

### ISSUE THREAD

**Issue by ArnaudDvs** [A-d-r-i/update_choco_packages#18]
The filen package has not been updated since v2.0.16; the latest version is [v2.0.24](https://github.com/FilenCloudDienste/filen-desktop/releases/tag/v2.0.24).

**Comment by A-d-r-i** [comment]
Thanks for the warning! Corrected with https://github.com/A-d-r-i/update_choco_packages/commit/424b7b177981e51fc2da3ce97a2174aa1dbcd84f
You can now download the new [2.0.24 version](https://community.chocolatey.org/packages/filen/2.0.24).
