### ISSUE TITLE
Mendeley Reference Manager Download URL changed

### ISSUE THREAD

**Issue by TK5-Tim** [A-d-r-i/update_choco_packages#19]
Hi Adri, 

Can you please check the download url for mendeley-reference-manager in the [VERIFICATION.txt](https://github.com/A-d-r-i/update_choco_packages/blob/main/mendeley-reference-manager/legal/VERIFICATION.txt)
It seems like in recent version the URL changed from 
`https://static.mendeley.com/bin/desktop/mendeley-reference-manager-2.119.0.exe`
to 
`https://static.mendeley.com/bin/desktop/mendeley-reference-manager-2.119.0-x64.exe`

Thanks!

**Comment by A-d-r-i** [comment]
Hi,
First of all, my apologies for the total lack of reaction on my part. I didn't realize the issue existed, excuse me!

Thanks to @goodv00 notification I corrected `VERIFICATION.txt` : bdf72e276bc793b9f31036e8e9197e456bb163f8

Thanks to all and sorry again!
